[package]
name = "wse_trader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
table-extract = "0.2.2"
reqwest = { version = "0.11", features = ["blocking"] }
